// src/views/details.vue
<template>
  <div >
    <div class="videoInfo">
    <div class="videoInfo-btnL"></div>
    <video id="video1" width="100%" height="100%" muted controls autoplay loop="loop">
        <source src="http://static.99114.com/static/cyw_video/festival_wine.mp4" type="video/mp4">
    </video>
</div>
<div class="videoBt">
    <p>日出-愿你有一个美好的今日时光!生活中有一个治愈式的美好</p>
    <div class="a">650M<span>2.2万次播放</span></div>
</div>
<div class="managementInfo">
    <div class="managementInfo-a">
        <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
        <div class="b">
            <p class="b1">管理者</p>
            <p class="b2">资源 45 </p>
        </div>
        <!-- <div class="c">已加入圈子</div> -->
        <div class="c">+ 加入圈子</div>
    </div>
    <div class="managementInfo-b">
        <div class="a">转存此资源，需消耗<span>35</span>金币</div>
        <div class="b">2020年7月31日发布</div>
    </div>
</div>
<div class="videogg">
    <img src="../assets/images/guangg.jpg" alt="">
</div>
<ul class="detailsContTab">
    <li class="tabDivActive"><span>评论</span>300</li>
    <li><span>点赞</span>2万</li>
    <li><span>分享</span>25</li>
    <li><span>转存</span>2</li>
</ul>
<div class="detailsContDiv">
    <!-- 评论 -->
    <ul class="detailsCont">
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">评论--小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
    <!-- 点赞 -->
    <ul class="detailsCont detailsContDianzan">
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">点赞--小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
    <!-- 分享 -->
    <ul class="detailsCont detailsContFenxiang ">
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">分享--小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
    <!-- 转存 -->
    <ul class="detailsCont detailsContDianzan">
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">转存---小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="../assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="viewMore">查看更多</div>





<div class="bottomBtn">
    <div class="form"><input type="text" placeholder="快捷评论"></div>
    <div class="pinglun"><span></span></div>
    <div class="dianzan"><span></span></div>
    <div class="fengxiang"><span></span></div>
    <div class="zhuancun"><span></span></div>
</div>
 
  </div>
</template>

<script>
// import { validUsername } from '@/utils/validate'
// import * as dd from 'dingtalk-jsapi' // 此方式为整体加载钉钉api，也可按需进行加载
// import dingConfig from '@/utils/ding-config' // 钉钉app的常量信息
// import axios from 'axios'
// import Cookies from 'js-cookie'

export default {
  name: 'index',
  // data() {
  //   const validateUsername = (rule, value, callback) => {
  //     if (!validUsername(value)) {
  //       callback(new Error('Please enter the correct user name'))
  //     } else {
  //       callback()
  //     }
  //   }
  //   const validatePassword = (rule, value, callback) => {
  //     if (value.length < 6) {
  //       callback(new Error('The password can not be less than 6 digits'))
  //     } else {
  //       callback()
  //     }
  //   }
  //   return {
  //     loginForm: {
  //       username: '',
  //       password: ''
  //     },
  //     loginRules: {
  //       username: [
  //         { required: true, trigger: 'blur', validator: validateUsername }
  //       ],
  //       password: [
  //         { required: true, trigger: 'blur', validator: validatePassword }
  //       ]
  //     },
  //     loading: false,
  //     passwordType: 'password',
  //     redirect: undefined
  //   }
  // },
  // watch: {
  //   $route: {
  //     handler: function(route) {
  //       this.redirect = route.query && route.query.redirect
  //     },
  //     immediate: true
  //   }
  // },
  // created() {
  //   this.dingdingLogin()
  // },
  // methods: {
  //   // loginbyVuex: function() {
  //   //   this.loading = true;
  //   //   this.$store.dispatch("user/getInfo",'').then(() => {
  //   //     if (this.name && this.token) {
  //   //       this.$router.push({ path: this.redirect || "/" });
  //   //     }
  //   //     this.loading = false;
  //   //   });
  //   // },
  //   dingdingLogin() {
  //     const _this = this
  //     dd.ready(function() {
  //       dd.runtime.permission.requestAuthCode({
  //         corpId: dingConfig.corpId, // 企业id
  //         onSuccess: function(info) {
  //           const code = info.code // 通过该免登授权码可以获取用户身份
  //           _this.getUserInfo(code)
  //         }
  //       })
  //     })
  //   },
  //   getUserInfo(code) {
  //     this.loading = true
  //     axios
  //       .get('/kpi/v1/user', {
  //         params: {
  //           code: code
  //         }
  //       })
  //       .then((res) => {
  //         const id = res.data.userid
  //         const name = res.data.name
  //         Cookies.set('request_user_id', id)
  //         Cookies.set('request_user_name', name)
  //         if (id && name) {
  //           this.loading = false
  //           if (id && name) {
  //             this.$router.push({ path: this.redirect || '/' })
  //           }
  //         }
  //       })
  //   },
  //   showPwd() {
  //     if (this.passwordType === 'password') {
  //       this.passwordType = ''
  //     } else {
  //       this.passwordType = 'password'
  //     }
  //     this.$nextTick(() => {
  //       this.$refs.password.focus()
  //     })
  //   },
  //   handleLogin() {
  //     this.$refs.loginForm.validate((valid) => {
  //       if (valid) {
  //         this.loading = true
  //         this.$store
  //           .dispatch('user/login', this.loginForm)
  //           .then(() => {
  //             this.$router.push({ path: this.redirect || '/' })
  //             this.loading = false
  //           })
  //           .catch(() => {
  //             this.loading = false
  //           })
  //       } else {
  //         console.log('error submit!!')
  //         return false
  //       }
  //     })
  //   }
  // }
}
</script>

<style >

</style>

// src/app/routes/details/details.component.ts
import { Component, OnInit, ViewChild, ElementRef, Injector } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { HttpService } from 'src/app/shared/services/http';

@Component({
	selector: 'video-details',
	templateUrl: './details.component.html',
	styleUrls: ['./details.component.css']
})

export class DetailsComponent implements OnInit {
	
	titles=["","设备绑定","姓名绑定"];
	title;
	id=1;
	data = [];
	loading = true;

	constructor(
		private route: ActivatedRoute,
		private http: HttpService,
		private router: Router
	) {
	}

	ngOnInit() {
		// this.id = +this.route.snapshot.data.id;
		// this.title = this.titles[this.id];

		// this.getMeetList();
	}

	meetClick(item):void{
        if(this.id==1){
            this.router.navigate(['/seatlist/code',{id:this.id,meetid:item.id}]);
        }else{
            this.router.navigate(['/seatlist/name',{id:this.id,meetid:item.id}]);
        }
	}
	
	getMeetList():void{
		this.loading = true;
		const params: Map<string, any> = new Map<string, any>();

		let url = "/roomtemplate/findAll";
		if(this.id == 2){
			url = "/meeting/findAll";
		}
		this.http.get(url, params, null).subscribe(data => {
			if(data.code == 0){
				this.data = data.data || [];
			}
			this.loading = false;
		}, error => {
			console.error(error);
			this.loading = false;
		});
	}

	// setSenseName(item:any): void {
	// 	const params: Map<string, any> = new Map<string, any>();
	// 	params.set('name', item.name);
	// 	params.set('id', item.id);

	// 	//判断名字是否已存在
	// 	let obj = this.senseList.filter(t=>t.name==item.name && !t.del && t.id != item.id) || "";
	// 	if(obj!=""){
	// 		this.httpError("新建大屏名称" + item.name + "已存在");
	// 		return;
	// 	}

	// 	//this.config.isLoading = true;
	// 	this.http.post('/config/modifyName', params, this.senseapi).subscribe(data => {
	// 		if (data.status == 200) {
	// 			item.editname = false;
	// 		} else {
	// 			this.httpError("修改大屏名称失败");
	// 			// this.fadeOutAction('系统错误,请稍后重试...', false);
	// 		}
	// 	}, error => {
	// 		//   this.fadeOutAction('系统错误,请稍后重试...', false);
	// 	});
	// }
	// delSenseById(item:any): void {
	// 	const params: Map<string, any> = new Map<string, any>();
	// 	// params.set('id', item.id);


	// 	//this.config.isLoading = true;
	// 	this.http.post('/config/del/'+item.id, params, this.senseapi).subscribe(data => {
	// 		this.isShowDeleteBox = false;
	// 		if (data.status == 200) {
	// 			item.del = true;
	// 			this.deladd++;
	// 		} else {
	// 			this.httpError("删除大屏失败");
	// 			// this.fadeOutAction('系统错误,请稍后重试...', false);
	// 		}
	// 	}, error => {
	// 		this.isShowDeleteBox = false;
	// 		//   this.fadeOutAction('系统错误,请稍后重试...', false);
	// 	});
	// }

	
}

<loading [isshow]="loading"></loading>
<div class="videoInfo">
    <div class="videoInfo-btnL"></div>
    <video id="video1" width="100%" height="100%" muted controls autoplay loop="loop">
        <source src="http://static.99114.com/static/cyw_video/festival_wine.mp4" type="video/mp4">
    </video>
</div>
<div class="videoBt">
    <p>日出-愿你有一个美好的今日时光!生活中有一个治愈式的美好</p>
    <div class="a">650M<span>2.2万次播放</span></div>
</div>
<div class="managementInfo">
    <div class="managementInfo-a">
        <div class="a"><img src="assets/images/headimg.png" alt=""></div>
        <div class="b">
            <p class="b1">管理者</p>
            <p class="b2">资源 45 </p>
        </div>
        <!-- <div class="c">已加入圈子</div> -->
        <div class="c">+ 加入圈子</div>
    </div>
    <div class="managementInfo-b">
        <div class="a">转存此资源，需消耗<span>35</span>金币</div>
        <div class="b">2020年7月31日发布</div>
    </div>
</div>
<div class="videogg">
    <img src="assets/images/guangg.jpg" alt="">
</div>
<ul class="detailsContTab">
    <li class="tabDivActive"><span>评论</span>300</li>
    <li><span>点赞</span>2万</li>
    <li><span>分享</span>25</li>
    <li><span>转存</span>2</li>
</ul>
<div class="detailsContDiv">
    <!-- 评论 -->
    <ul class="detailsCont">
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">评论--小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">感谢分享</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
    <!-- 点赞 -->
    <ul class="detailsCont detailsContDianzan">
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">点赞--小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">点赞了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
    <!-- 分享 -->
    <ul class="detailsCont detailsContFenxiang ">
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">分享--小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">
                    <div class="nc">333小胖妈妈的生活</div>
                    <div class="jb">获得<span>5</span>金币</div>
                </div>
                <div class="b2">
                    <div class="pl">分享到了微信</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
    <!-- 转存 -->
    <ul class="detailsCont detailsContDianzan">
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">转存---小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/headimg.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
        <li>
            <div class="a"><img src="assets/images/touxiang.png" alt=""></div>
            <div class="b">
                <div class="b1">小胖妈妈的生活</div>
                <div class="b2">
                    <div class="pl">转存了此资源</div>
                    <div class="time">10-1 12:12</div>
                </div>
            </div>
        </li>
    </ul>
</div>
<div class="viewMore">查看更多</div>





<div class="bottomBtn">
    <div class="form"><input type="text" placeholder="快捷评论"></div>
    <div class="pinglun"><span></span></div>
    <div class="dianzan"><span></span></div>
    <div class="fengxiang"><span></span></div>
    <div class="zhuancun"><span></span></div>
</div>
